### PR TITLE
Barcode updates

### PR DESCRIPTION
**Pull request by thuyvyng**
Screenshots in slack

### CODE REVIEW

**Comment by MarkleyO** [comment]
Looks like everything seems to work, however I noticed that I would get an error about a missing favicon, however this doesn't sound that important. There were also the expected issues with speed. One other problem is it requires that example JSON that I sent you, so I don't think anyone else can test it unless they have that. However functionally everything seems fine

**Review by MarkleyO — APPROVED** [review]

**Comment by MarkleyO** [comment]
Another note, I'm assuming we'll have to make some changes to the default values which the sliders are given.

**Comment by thuyvyng** [comment]
> Looks like everything seems to work, however I noticed that I would get an error about a missing favicon, however this doesn't sound that important. There were also the expected issues with speed. One other problem is it requires that example JSON that I sent you, so I don't think anyone else can test it unless they have that. However functionally everything seems fine

what was the error?

**Comment by thuyvyng** [comment]
> Another note, I'm assuming we'll have to make some changes to the default values which the sliders are given.

what do you mean?

**Comment by thuyvyng** [comment]
Screen Shot 2021-04-20 at 1 30 42 PM

I implemented the sorting that Dr. Kahng and I discussed in the slack channel

**Review by laurajjiang — APPROVED** [review]

**Pull request merged**
