### PR TITLE
rendering vector and barcode vis on notebooks

### PR DESCRIPTION
**Pull request by wnsgur4322**
with python library, I rendered vector (iris data) and barcode visualizations on notebooks.
I tried to connect google firebase storage on barcode.html due to loading huge json file (over 300MB), but it doesn't work on .html file.

### CODE REVIEW

**Comment by thuyvyng** [comment]
Screen Shot 2021-04-26 at 11 22 37 AM
 
Is there were the visualization for vector visualizations is supposed to be? It doesn't run for me

**Comment by thuyvyng** [comment]
Screen Shot 2021-04-26 at 11 24 38 AM

I re-ran the notebook again and it appeared, does anyone else have that issue?

**Comment by thuyvyng** [comment]
Screen Shot 2021-04-26 at 11 45 53 AM
Furthermore, this doesn't show up for me. Am i missing something?

**Review by thuyvyng — CHANGES_REQUESTED** [review]
Comments left above, re-request me when you address these issues

discussed in slack: add barcode to hub text w/ updated barcode visualizations in my PR

**Comment by wnsgur4322** [comment]
> Screen Shot 2021-04-26 at 11 45 53 AM
> Furthermore, this doesn't show up for me. Am i missing something?

for barcode, it needs nn epoch json file on path "./libraries/simple_nn_epoch_sorted.json"

**Comment by MarkleyO** [comment]
> Screen Shot 2021-04-26 at 11 45 53 AM
> Furthermore, this doesn't show up for me. Am i missing something?

This I'm aware of, I'll see if throwing a line to load the d3 source library into the notebook, before loading in any of the visualizations from python files does anything to help this. and yes it should be hub rather than simple

**Comment by thuyvyng** [comment]
apparently you have a conflicting file, could u fix that?

**Review by thuyvyng — DISMISSED** [review]
merge error, could u fix

**Review by thuyvyng — APPROVED** [review]
You showed both the barcode visualization & iris working in our wednesday meeting and it looked great, i think we could do the barcode stuff dr kahng talked about in a different PR (generating the json file) also you know you can add the json file using git LFS (large file system so could u do that instead of the google cloud thingy)

**Review by laurajjiang — APPROVED** [review]

**Pull request merged**
