### PR TITLE
Logistic Regression notebook

### PR DESCRIPTION
**Pull request by wnsgur4322**
I made logistic regression notebook with tensorflow 2.x
it also creates json file in the end of the notebook.
Let me know if you have any questions.

Thanks

### CODE REVIEW

**Review by thuyvyng — CHANGES_REQUESTED** [review]
I found some errors in the code.
You named a variable x_train but later on you try to call train_x. it's in code block 25

you did this a couple a couple of times in this block so could you fix that?


# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto')
classifier.fit(x_train, y_train)

**Comment by thuyvyng** [comment]
Also this might not be a request change for you but could we add in the interactive confusion matrix instead? Maybe Owen can do that since hes most familiar with it.

**Comment by thuyvyng** [comment]
Side note 2, we will have to integrate my visualization for chapter 1 later but we may wanna discuss how later on/ refactor my code for that

**Comment by wnsgur4322** [comment]
I changed last blocks, but I left the last two blocks (under the line) as an alternative way to implement logistic regression. Since it is just using built-in library, it could be wrong for our project purpose. So, I will ask about this on incoming meeting.

Thanks for reviews !

> I found some errors in the code.
> You named a variable x_train but later on you try to call train_x. it's in code block 25
> 
> you did this a couple a couple of times in this block so could you fix that?
> 
> # Fitting Logistic Regression to the Training set
> from sklearn.linear_model import LogisticRegression
> classifier = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto')
> classifier.fit(x_train, y_train)

**Review by thuyvyng — APPROVED** [review]

**Comment by MarkleyO** [comment]
> Also this might not be a request change for you but could we add in the interactive confusion matrix instead? Maybe Owen can do that since hes most familiar with it.

I think theres some issues with this, I have it on my local branch and working, however the counts don't seem to add up properly? The number of entries in each cell of the matrix aren't the same between the d3 powered matrix we have and the seaborn plot at the end of this notebook. Other than this the model itself seems to be fine.

**Review by MarkleyO — APPROVED** [review]

**Pull request merged**
