### PR TITLE
adding iris + barcodes visualization to site

### PR DESCRIPTION
**Pull request by laurajjiang**
+ add iris vis to the site
+ add barcode vis to the site 
 
- need to fix barcode spacing on the site, cosine similarity (will talk to Thuy-Vy)

to run, add barcodes.json to the src/assets/barcode_visualization folders

Screen Shot 2021-05-04 at 11 08 03 AM
Screen Shot 2021-05-04 at 11 08 15 AM

### CODE REVIEW

**Comment by thuyvyng** [comment]
Screen Shot 2021-05-04 at 11 25 23 AM
Is there a way you could make the visualization fit the entire content of the page? or atleast make it centered?

it seems to be centered on chapter 2 but not chapter 1

**Comment by thuyvyng** [comment]
Screen Shot 2021-05-04 at 12 01 39 PM

@laurajjiang within barcode.css add td {min-width: 10px}

**Comment by thuyvyng** [comment]
could you also put like padding or margin between the different types of columns (sentences, cosine sim, barcode) when i implemented the sentences it should have ... into overflow but its not showing up here

**Comment by thuyvyng** [comment]
Screen Shot 2021-05-04 at 12 06 07 PM
small complaint, the view on github button is hard to see

**Review by thuyvyng — CHANGES_REQUESTED** [review]
Comments left above: let me know if you need more help. 

Still confused on the cosine similarity so I might come back to fix that but idk if its important at this point, i think the other comments should be pretty easy tho

**Comment by thuyvyng** [comment]
Screen Shot 2021-05-04 at 4 51 02 PM
made it wider to fit the screen better & added text-overflow ellipses

**Comment by thuyvyng** [comment]
cosine similarity does not work, when i click on a sentence it should show it has a cosine similarity of 1 with itself. thats not true in the website

**Review by thuyvyng — APPROVED** [review]
Looks pretty good to me but the file for the barcode visualization should have more sentences & have more bars. This doesn't need to be fixed here but it should get fixed also the github button is still weird

**Comment by MarkleyO** [comment]
I'm not sure if it's been changed yet, but selecting certain values for the 'num sentences' meter on the barcode visualization, as well as certain values on the 'confidence' value on the confusion matrix slider cause the site to crash

**Comment by laurajjiang** [comment]
> I'm not sure if it's been changed yet, but selecting certain values for the 'num sentences' meter on the barcode visualization, as well as certain values on the 'confidence' value on the confusion matrix slider cause the site to crash

will fix in a separate PR - the confusion matrix code should get updated anyways in accordance with your changes too

**Pull request merged**
