### PR TITLE
update chapter 1, add notebooks to repo

### PR DESCRIPTION
**Pull request by laurajjiang**
- added chapter 1 to site 
- migrated notebooks repo over to this repo

### CODE REVIEW

**Review by thuyvyng — CHANGES_REQUESTED** [review]
For naive bayes text classification, its not updated with most recent changes. There are some errors - the text files dont exist bc the paths are incorrect (they'e missing dataset/) and it has the incorrect code for the json making for the confusion matrix (you can tell because the confusion matrix doesnt update correctly and because it doesnt say the value of the slider and because theres a giant chunk of javascript in the notebook)

**Comment by thuyvyng** [comment]
Text classification w/ hub doesn't work for me either. It breaks on cell 5 -- comparing this code with the one on the other repo it seems as on this repo the csv is in a zip but on the other repo its not (the other repo works for me).

**Comment by thuyvyng** [comment]
Questions about site:
1. The links on chapter 1 don't work. Is this correct and are these gonna be put in later? Just wanted to make sure.
2. I sort of think Chapter 1 should be longer and I think stuff about cleaning up your data is important. We may wanna discuss this as a team later and also how to explain steps in naive bayes better as well.
 
Overall, the website really awesome. The confusion matrix format side by side looks really clean and nice. We may wanna add more of the interactions (confidence scores later on), but nice job!!

**Comment by MarkleyO** [comment]
> Text classification w/ hub doesn't work for me either. It breaks on cell 5 -- comparing this code with the one on the other repo it seems as on this repo the csv is in a zip but on the other repo its not (the other repo works for me).

ok, I think i've re-implemented the parts that didnt migrate successfully over, I'm doing one last re-run to check its good, then committing the changes. Also the axis are still flipped on the confusion matrix.

**Comment by thuyvyng** [comment]
> > Text classification w/ hub doesn't work for me either. It breaks on cell 5 -- comparing this code with the one on the other repo it seems as on this repo the csv is in a zip but on the other repo its not (the other repo works for me).
> 
> ok, I think i've re-implemented the parts that didnt migrate successfully over, I'm doing one last re-run to check its good, then committing the changes. Also the axis are still flipped on the confusion matrix.

Oh that's just the way Dr. Kahng liked it, I can flip it if you want but I think the typical way confusion matricies work is perfect classsification is diagonal from top left corner to bottom right corner which is what we have

**Comment by thuyvyng** [comment]
Screen Shot 2021-02-03 at 3 40 46 PM
We may want to either make the dataset smaller or change the size of the svg and visualizations because the matrix is way too large. We can do that as a later pr tho, we should discuss

**Review by thuyvyng — APPROVED** [review]

**Review by MarkleyO — APPROVED** [review]

**Pull request merged**
